#!/usr/bin/env bash
#
# Updates docker files for major postgres versions
#
# Usage:
#   > ./update.sh
#

versions=( "$@" )
if [ ${#versions[@]} -eq 0 ]; then
    versions=( */ )
fi
versions=( "${versions[@]%/}" )

read -r -d '' generated_warning <<EOF
#
# THIS FILE IS GENERATED BY "update.sh"
# DO NOT EDIT
#
EOF

for version in "${versions[@]}"; do

  for variant in '' 'alpine'; do

    if [ "$variant" == "" ]; then
      template="Dockerfile-debian.template"
    else
      template="Dockerfile-$variant.template"
    fi

    echo "$generated_warning" > "$version/$variant/Dockerfile"
    sed -e 's/%%PG_VERSION%%/'"$version"'/g' \
        "$template" >> "$version/$variant/Dockerfile"

  done

done
